# Generated by Django 3.2.3 on 2021-06-07 13:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0002_resultado_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 7, 13, 19, 8, 876173, tzinfo=utc)),
        ),
    ]
