# Generated by Django 3.2 on 2021-05-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='puntuacion_para_pasar',
            field=models.IntegerField(help_text='Puntuación necesaria para aprobar'),
        ),
    ]
